name: flutter_widgets
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #shrine_images: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/alert_dialog.png
    - assets/align.jpg
    - assets/appbar.png
    - assets/aspect_ratio.jpg
    - assets/baseline.jpg
    - assets/bottom_navigation.png
    - assets/bottom_sheet.png
    - assets/card.png
    - assets/center.jpg
    - assets/checkbox.png
    - assets/chip.png
    - assets/column.jpg
    - assets/constrained_box.jpg
    - assets/container.jpg
    - assets/cupertino_action_sheet.png
    - assets/cupertino_activity_indicator.png
    - assets/cupertino_alert_dialog.png
    - assets/cupertino_button.png
    - assets/cupertino_date_picker.png
    - assets/cupertino_dialog_action.png
    - assets/cupertino_dialog.png
    - assets/cupertino_fullscreen_dialog_transition.png
    - assets/cupertino_navigation_bar.jpg
    - assets/cupertino_page_scaffold.png
    - assets/cupertino_page_transition.png
    - assets/cupertino_picker.png
    - assets/cupertino_segmented_control.jpg
    - assets/cupertino_slider.jpg
    - assets/cupertino-switch.png
    - assets/cupertino_tab_scaffold.png
    - assets/cupertino_tabbar.jpg
    - assets/cupertino_tabview.png
    - assets/cupertino_textfield.png
    - assets/cupertino_timer_picker.png
    - assets/data_table.png
    - assets/diamond.png
    - assets/divider.png
    - assets/expansion_panel.png
    - assets/fab.png
    - assets/flat_button.png
    - assets/flutter_logo.png
    - assets/gridview.png
    - assets/icon_button.png
    - assets/image.jpg
    - assets/linear_progress_indicator.png
    - assets/list_tile.png
    - assets/listview.jpg
    - assets/material_app.png
    - assets/navigation_drawer.png
    - assets/padding.jpg
    - assets/pickers.png
    - assets/popup_menu_button.png
    - assets/radio_button.png
    - assets/raised_button.png
    - assets/refresh_indicator.jpg
    - assets/row.jpg
    - assets/scaffold.png
    - assets/silver_appbar.png
    - assets/simple_dialog.png
    - assets/sized_box.jpg
    - assets/slanted_menu.png
    - assets/slider.png
    - assets/snackbar.png
    - assets/stack.jpg
    - assets/stepper.png
    - assets/switch.png
    - assets/tabbar_view.png
    - assets/tabbar.png
    - assets/text.jpg
    - assets/textfield.png
    - assets/tooltip.png
    - assets/transform.jpg
    - assets/coby/0-0.jpg
    - assets/coby/1-0.jpg
    - assets/coby/2-0.jpg
    - assets/coby/3-0.jpg
    - assets/coby/4-0.jpg
    - assets/coby/5-0.jpg
    - assets/coby/6-0.jpg
    - assets/coby/7-0.jpg
    - assets/coby/8-0.jpg
    - assets/coby/9-0.jpg
    - assets/coby/10-0.jpg
    - assets/coby/11-0.jpg
    - assets/coby/12-0.jpg
    - assets/coby/13-0.jpg
    - assets/coby/14-0.jpg
    - assets/coby/15-0.jpg
    - assets/coby/16-0.jpg
    - assets/coby/17-0.jpg
    - assets/coby/18-0.jpg
    - assets/coby/19-0.jpg
    - assets/coby/20-0.jpg
    - assets/coby/21-0.jpg
    - assets/coby/22-0.jpg
    - assets/coby/23-0.jpg
    - assets/coby/24-0.jpg
    - assets/coby/25-0.jpg
    - assets/coby/26-0.jpg
    - assets/coby/27-0.jpg
    - assets/coby/28-0.jpg
    - assets/coby/29-0.jpg
    - assets/coby/30-0.jpg
    - assets/coby/31-0.jpg
    - assets/coby/32-0.jpg
    - assets/coby/33-0.jpg
    - assets/coby/34-0.jpg
    - assets/coby/35-0.jpg
    - assets/coby/36-0.jpg
    - assets/coby/37-0.jpg
    - assets/sections/layout.png
    - assets/sections/basics.png
    - assets/sections/DAM.jpg
    - assets/sections/inputs.png
    - assets/sections/logo-apple.jpg
    - assets/sections/mio-design.png
    - assets/sections/scrolling.jpeg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
          style: italic
    #- family: Lora
    #  fonts:
    #    - asset: fonts/Lora/
    #      style: italic
    #- family: Oswald
    #  fonts:
    #    - asset: fonts/Oswald/
    #      style: italic
    #- family: Roboto Slab
    #  fonts:
    #    - asset: fonts/Roboto_Slab/
    #      style: italic












  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

